wordpress:
  image: wordpress:4.4
  links:
    - db:mysql
  ports:
    - 8888:80
  environment:
    WORDPRESS_DB_HOST: 192.168.33.131
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_PASSWORD: root


db:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: root
  ports:
    - 3306:3306